<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="./css/DASHBOARD.css">
  <title>Navbar Dinámico</title>

</head>
<body>

<div class="navbar">
  <a class="active" href="#">Inicio</a>
  <a href="#">CREDITO</a>
  <a href="#">SERVICIO</a>
  <a href="EMPLEADO.PHP">EMPLEADOS</a>
</div>

</body>
</html>
